# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-alpine

# Install dependencies
RUN apk add --no-cache gcc musl-dev linux-headers

# Set working directory
WORKDIR /app

# Copy requirements from pyproject.toml (we use pip to install dependencies)
# We assume that dependencies are declared in pyproject.toml
COPY pyproject.toml ./
COPY poker.py ./
COPY uv.lock ./

# Install pip dependencies
RUN pip install --no-cache-dir "mcp[cli]>=1.3.0" httpx>=0.28.1

# Command to run the MCP server
ENTRYPOINT ["python", "poker.py"]
